/// Defines the reason why the model stopped generating tokens.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FinishReason {
    /// Default value. This value is unused.
    Unspecified = 0,
    /// Natural stop point of the model or provided stop sequence.
    Stop = 1,
    /// The maximum number of tokens as specified in the request was reached.
    MaxTokens = 2,
    /// The response candidate content was flagged for safety reasons.
    Safety = 3,
    /// The response candidate content was flagged for recitation reasons.
    Recitation = 4,
    /// The response candidate content was flagged for using an unsupported
    /// language.
    Language = 6,
    /// Unknown reason.
    Other = 5,
    /// Token generation stopped because the content contains forbidden terms.
    Blocklist = 7,
    /// Token generation stopped for potentially containing prohibited content.
    ProhibitedContent = 8,
    /// Token generation stopped because the content potentially contains
    /// Sensitive Personally Identifiable Information (SPII).
    Spii = 9,
    /// The function call generated by the model is invalid.
    MalformedFunctionCall = 10,
    /// Token generation stopped because generated images contain safety
    /// violations.
    ImageSafety = 11,
}
impl FinishReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FINISH_REASON_UNSPECIFIED",
            Self::Stop => "STOP",
            Self::MaxTokens => "MAX_TOKENS",
            Self::Safety => "SAFETY",
            Self::Recitation => "RECITATION",
            Self::Language => "LANGUAGE",
            Self::Other => "OTHER",
            Self::Blocklist => "BLOCKLIST",
            Self::ProhibitedContent => "PROHIBITED_CONTENT",
            Self::Spii => "SPII",
            Self::MalformedFunctionCall => "MALFORMED_FUNCTION_CALL",
            Self::ImageSafety => "IMAGE_SAFETY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FINISH_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "STOP" => Some(Self::Stop),
            "MAX_TOKENS" => Some(Self::MaxTokens),
            "SAFETY" => Some(Self::Safety),
            "RECITATION" => Some(Self::Recitation),
            "LANGUAGE" => Some(Self::Language),
            "OTHER" => Some(Self::Other),
            "BLOCKLIST" => Some(Self::Blocklist),
            "PROHIBITED_CONTENT" => Some(Self::ProhibitedContent),
            "SPII" => Some(Self::Spii),
            "MALFORMED_FUNCTION_CALL" => Some(Self::MalformedFunctionCall),
            "IMAGE_SAFETY" => Some(Self::ImageSafety),
            _ => None,
        }
    }
}
