#[derive(Clone, PartialEq, ::prost::Oneof)]
pub enum Data {
    /// Inline text.
    #[prost(string, tag = "2")]
    Text(::prost::alloc::string::String),
    /// Inline media bytes.
    #[prost(message, tag = "3")]
    InlineData(super::Blob),
    /// A predicted `FunctionCall` returned from the model that contains
    /// a string representing the `FunctionDeclaration.name` with the
    /// arguments and their values.
    #[prost(message, tag = "4")]
    FunctionCall(super::FunctionCall),
    /// The result output of a `FunctionCall` that contains a string
    /// representing the `FunctionDeclaration.name` and a structured JSON
    /// object containing any output from the function is used as context to
    /// the model.
    #[prost(message, tag = "5")]
    FunctionResponse(super::FunctionResponse),
    /// URI based data.
    #[prost(message, tag = "6")]
    FileData(super::FileData),
    /// Code generated by the model that is meant to be executed.
    #[prost(message, tag = "9")]
    ExecutableCode(super::ExecutableCode),
    /// Result of executing the `ExecutableCode`.
    #[prost(message, tag = "10")]
    CodeExecutionResult(super::CodeExecutionResult),
}
