name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: Test Suite (${{ matrix.os }} - ${{ matrix.rust }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, '1.86.0']
        include:
          - rust: stable
            profile: default
          - rust: '1.86.0'
            profile: minimal

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v2

    # Format check
    - run: cargo fmt --all -- --check

    - run: cargo clippy --all-targets --all-features -- -D warnings

    # Testing
    - name: Test main crate
      run: cargo test -p google-ai-rs --all-features

    - name: Test derive crate
      run: cargo test -p google-ai-schema-derive --all-features

  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - run: cargo doc --no-deps --all-features --workspace